/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

/**
 *
 * @author user
 */
public class JFMenu extends javax.swing.JFrame {

    /**
     * Creates new form Operaciones
     */
    JFSuma jfsuma;
    JFProducto jfproducto;
    JFOperacionesD jfoperacionesd;
    JFOperacionABC jfmultiplicacionABC;
    public JFMenu() {
        initComponents();
        //this.setExtendedState(MAXIMIZED_BOTH);
        jfsuma=new JFSuma();
        jfproducto=new JFProducto();
        jfoperacionesd = new JFOperacionesD();
        jfmultiplicacionABC = new JFOperacionABC();
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMISalir = new javax.swing.JMenuItem();
        jMICancelar = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMISumaMatrices = new javax.swing.JMenuItem();
        jMIProductoMatrices = new javax.swing.JMenuItem();
        jMIOperacionesDiagonales = new javax.swing.JMenuItem();
        jMIMultiplicacion1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("File");

        jMISalir.setText("Salir");
        jMISalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMISalirActionPerformed(evt);
            }
        });
        jMenu1.add(jMISalir);

        jMICancelar.setText("Cancelar");
        jMenu1.add(jMICancelar);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        jMISumaMatrices.setText("Suma Matrices");
        jMISumaMatrices.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMISumaMatricesActionPerformed(evt);
            }
        });
        jMenu2.add(jMISumaMatrices);

        jMIProductoMatrices.setText("Producto Matrices");
        jMIProductoMatrices.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIProductoMatricesActionPerformed(evt);
            }
        });
        jMenu2.add(jMIProductoMatrices);

        jMIOperacionesDiagonales.setText("Operaciones Diagonales");
        jMIOperacionesDiagonales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIOperacionesDiagonalesActionPerformed(evt);
            }
        });
        jMenu2.add(jMIOperacionesDiagonales);

        jMIMultiplicacion1.setText("multiplicacion 1: C= A*2B");
        jMIMultiplicacion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIMultiplicacion1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMIMultiplicacion1);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMISalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMISalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMISalirActionPerformed

    private void jMISumaMatricesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMISumaMatricesActionPerformed
        this.jfsuma.setVisible(true);
    }//GEN-LAST:event_jMISumaMatricesActionPerformed

    private void jMIProductoMatricesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIProductoMatricesActionPerformed
        this.jfproducto.setVisible(true);
    }//GEN-LAST:event_jMIProductoMatricesActionPerformed

    private void jMIOperacionesDiagonalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIOperacionesDiagonalesActionPerformed
        this.jfoperacionesd.setVisible(true);
    }//GEN-LAST:event_jMIOperacionesDiagonalesActionPerformed

    private void jMIMultiplicacion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIMultiplicacion1ActionPerformed
        this.jfmultiplicacionABC.setVisible(true);
    }//GEN-LAST:event_jMIMultiplicacion1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem jMICancelar;
    private javax.swing.JMenuItem jMIMultiplicacion1;
    private javax.swing.JMenuItem jMIOperacionesDiagonales;
    private javax.swing.JMenuItem jMIProductoMatrices;
    private javax.swing.JMenuItem jMISalir;
    private javax.swing.JMenuItem jMISumaMatrices;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
