
package Interfaces;
import java.awt.Graphics;
import java.awt.Color;
import javax.swing.JPanel;


public class JPDibujoArcoiris extends JPanel {

    
    final Color VIOLETA= new Color (128,0,128);
    final Color INDIGO = new Color (75,0,130);
    
    private Color colores[]={Color.WHITE, Color.WHITE, Color.WHITE, VIOLETA,
    INDIGO, Color.BLUE, Color.GREEN, Color.YELLOW, Color.ORANGE, Color.RED};
    
    public JPDibujoArcoiris() {
        
        
        //initComponents();
        setBackground(Color.WHITE);
    }
    
    public void paintComponent(Graphics g)
    {
        super.paintComponents(g);
        int radio = 20;
        int centroX = getWidth()/2;
        int centroY = getHeight()-10;
        //DIBUJA arcos desde el mas exterior
        
        for(int contador = colores.length; contador > 0; contador--)
        {
            g.setColor(colores[contador - 1]);
            g.fillArc(centroX - contador *radio, centroY-contador*radio,
                    contador*radio*2,contador*radio*2,0,180);
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
