/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

/**
 *
 * @author user
 */
import Source.Vector;
import javax.swing.JOptionPane;
public class JFVector extends javax.swing.JFrame {

    // Atributos de CLASE
    private Vector vector;
    private String salida;
    private String nuevoValor;
    /**
     * Creates new form JFVector
     */
   
    public JFVector() {
        initComponents();
        this.setLocationRelativeTo(null);
        jCBOperaciones.setVisible(false);
        this.jBAceptar.setVisible(false);
        this.jBIngresar.setVisible(false);
        this.jLIngresarV.setVisible(false);
        this.jTFBuscar.setVisible(false);
        salida = "";
        nuevoValor ="";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTFDimension = new javax.swing.JTextField();
        jLDimension = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTAResultado = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jBAceptar = new javax.swing.JButton();
        jBSalir = new javax.swing.JButton();
        jBNuevo = new javax.swing.JButton();
        jCBOperaciones = new javax.swing.JComboBox<>();
        jTFBuscar = new javax.swing.JTextField();
        jLIngresarV = new javax.swing.JLabel();
        jBIngresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTFDimension.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFDimensionActionPerformed(evt);
            }
        });

        jLDimension.setText("Dimensión");

        jTAResultado.setColumns(20);
        jTAResultado.setRows(5);
        jScrollPane1.setViewportView(jTAResultado);

        jLabel2.setText("Resultado");

        jBAceptar.setText("Aceptar");
        jBAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAceptarActionPerformed(evt);
            }
        });

        jBSalir.setText("Salir");
        jBSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSalirActionPerformed(evt);
            }
        });

        jBNuevo.setText("Nuevo");
        jBNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBNuevoActionPerformed(evt);
            }
        });

        jCBOperaciones.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sumatoria de elementos ", "Sumatoria de numeros primos", "Contar números perfectos ", "Clasificar el Vector \t", "Buscar el número mayor", "Buscar el número menor", "Suma Binaria" }));
        jCBOperaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBOperacionesActionPerformed(evt);
            }
        });

        jLIngresarV.setText("Ingresar Valor de Busqueda");

        jBIngresar.setText("Ingresar");
        jBIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBIngresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBAceptar)
                        .addGap(18, 18, 18)
                        .addComponent(jBSalir)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jCBOperaciones, 0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLDimension)
                            .addComponent(jBIngresar))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTFBuscar, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTFDimension)))
                    .addComponent(jLIngresarV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBNuevo)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTFDimension, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLDimension))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTFBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBIngresar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBAceptar)
                            .addComponent(jBSalir))
                        .addGap(18, 18, 18)
                        .addComponent(jLIngresarV))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBNuevo)
                    .addComponent(jCBOperaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(106, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTFDimensionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFDimensionActionPerformed
        this.jBAceptar.setVisible(true);
        this.jTAResultado.setText("");
        this.jTFDimension.requestFocus();
        jCBOperaciones.setVisible(true); 
    }//GEN-LAST:event_jTFDimensionActionPerformed

    private void jBAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAceptarActionPerformed
        this.jTFDimension.requestFocus();
        if(nuevoValor == ""){
            try
            {
                vector = new Vector(Integer.parseInt(this.jTFDimension.getText()));
                vector.setVector();   
            }catch(Exception e)
            {
                JOptionPane.showMessageDialog(null,"Solo números enteros porfavor");
                this.jTFDimension.setText("");
                this.jTFDimension.requestFocus();    
            }     
        }
        
        salida += "\n" + vector.toString();
        this.jTAResultado.setText(salida);
        this.jCBOperaciones.setVisible(true);
    }//GEN-LAST:event_jBAceptarActionPerformed

    private void jBSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jBSalirActionPerformed

    private void jBNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBNuevoActionPerformed
        this.jTFDimension.setText("");
        this.jTAResultado.setText("");
        nuevoValor = "";
        this.jTFDimension.requestFocus();
        salida+="\n";
        jCBOperaciones.setVisible(false);
        this.jBAceptar.setVisible(false);
        this.jBIngresar.setVisible(false);
        this.jLIngresarV.setVisible(false);
        this.jTFBuscar.setVisible(false);
    }//GEN-LAST:event_jBNuevoActionPerformed

    private void jCBOperacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBOperacionesActionPerformed
        switch(this.jCBOperaciones.getSelectedIndex())
        {
            case 0:
            {
                salida += "\n Suma de Elementos: " + vector.sumarElementos();
                nuevoValor = "valor antiguo";
                
                break;
            }
            case 1:
            {
                salida+= "\n Suma de Primos: " + vector.sumaPrimos();
                nuevoValor = "valor antiguo";
                break;
            }
            case 2:
            {
                salida+= "\n En total estan: " + vector.contarNumPerfecto()+ " numeros "
                        + " perfectos";
                nuevoValor = "valor antiguo";
                break;
                
            }
            case 3:
            {
                salida+= "\n Se ha clasidicado el vector de mayor a menor: ";
                vector.clasificarVector();
                nuevoValor = "valor antiguo";
                break;
                
            }
            case 4:  
            {
                salida+= "\n El mayor número es: " + vector.numMayor();
                nuevoValor = "valor antiguo";
                break;
            }
            case 5:
            {
                salida+= "\n El menor número es: " + vector.numMenor();
                nuevoValor = "valor antiguo";
                break;
            }
            case 6:
            {
                this.jTFDimension.setVisible(false);
                this.jLDimension.setVisible(false);
                this.jBAceptar.setVisible(false);
                this.jBNuevo.setVisible(false);
                this.jCBOperaciones.setVisible(false);
                this.jBIngresar.setVisible(true);
                this.jLIngresarV.setVisible(true);
                this.jTFBuscar.setVisible(true);
                break;
            }
        }
    }//GEN-LAST:event_jCBOperacionesActionPerformed

    private void jBIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBIngresarActionPerformed
        try{
            
           int a = Integer.parseInt(this.jTFBuscar.getText());
           int indice = vector.busquedaBinaria(a);
           if(indice >= 0){
                salida += "\n El valor que buscas para el ordenado  vector: " + vector
                        + "\n probablemente se encuentre en "
                        + "la posicion: " + indice;
           }else{
                salida += "\n El valor que buscas para el ordenado  vector: " + vector
                        + "\n no se a encontrado ";
                        
           }
           this.jTAResultado.setText(salida);
           this.jTFDimension.setVisible(true);
           this.jLDimension.setVisible(true);
           this.jBAceptar.setVisible(true);
           this.jBNuevo.setVisible(true);
           this.jCBOperaciones.setVisible(true);
           this.jBIngresar.setVisible(false);
           this.jLIngresarV.setVisible(false);
           this.jTFBuscar.setVisible(false);
           
           
            
        }catch(NumberFormatException e)
        {
            JOptionPane.showMessageDialog(null, "ingrese un número");
            this.jTFBuscar.setText("");
            this.jTFBuscar.requestFocus();
        }
    }//GEN-LAST:event_jBIngresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFVector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFVector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFVector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFVector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFVector().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAceptar;
    private javax.swing.JButton jBIngresar;
    private javax.swing.JButton jBNuevo;
    private javax.swing.JButton jBSalir;
    private javax.swing.JComboBox<String> jCBOperaciones;
    private javax.swing.JLabel jLDimension;
    private javax.swing.JLabel jLIngresarV;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTAResultado;
    private javax.swing.JTextField jTFBuscar;
    private javax.swing.JTextField jTFDimension;
    // End of variables declaration//GEN-END:variables
}
