/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import java.awt.Color;
import java.awt.Graphics;
import java.util.Random;
import javax.swing.JPanel;
import usoDeObjetosConGráficos.MiLinea;
public class JPanelDibujo extends JPanel {

    private Random numerosAleatorios = new Random();
    private MiLinea lineas[];
    
    public JPanelDibujo() {
        //initComponents();// carga todos los objetos del JFrame --> JPanel al ejecutar el programa
        super();//Cuando utilizas herencia en Java, en los constructores que declaras en las clases hijas siempre deben llamar a super(args) el cual hace referencia a un constructor de clase padre
        setBackground(Color.WHITE);// en los constructores de una clase hija, al menos un constructor debe llamar a super()
        lineas= new MiLinea[5 + numerosAleatorios.nextInt(5)];
        for(int cuenta = 0; cuenta < lineas.length; cuenta++)
        {
            int x1=numerosAleatorios.nextInt(300);
            int y1= numerosAleatorios.nextInt(300);
            int x2= numerosAleatorios.nextInt(300);
            int y2= numerosAleatorios.nextInt(300);
            Color color= new Color(numerosAleatorios.nextInt(256),
                  numerosAleatorios.nextInt(256),numerosAleatorios.nextInt(256));
            lineas[cuenta]= new MiLinea(x1,x2,y1,y2,color);
        }
    }
    
    public void paintComponent( Graphics g)
    {
        super.paintComponent(g);
        for(MiLinea linea:lineas){
            linea.dibujar(g);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
